// Navbar
export const HANDLE_MENU = 'HANDLE_MENU'

// Skills Type
export const INCREMENT_STEP = 'INCREMENT_STEP'
export const DECREMENT_STEP = 'DECREMENT_STEP'
export const DYNAMIC_ACTIVE_STEP = 'DYNAMIC_ACTIVE_STEP'
export const HANDLE_MODAL = 'HANDLE_MODAL'

// Portfolio  Type
export const HANDLE_ITEM_MODAL = 'HANDLE_ITEM_MODAL'
export const HANDLE_TAB_CLICK = 'HANDLE_TAB_CLICK'
export const HANDLE_PAGINATION = 'HANDLE_PAGINATION'
export const MODAL_PAGE_INCREMENT_AND_DECREMENT = 'MODAL_PAGE_INCREMENT_AND_DECREMENT'
export const HANDLE_PORTFOLIO_SEARCH = 'HANDLE_PORTFOLIO_SEARCH'