export const IS_LOADING_OPENED = 'IS_LOADING_OPENED'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
// Navbar
export const HANDLE_MENU = 'HANDLE_MENU'

// Skills Types
export const INCREMENT_STEP = 'INCREMENT_STEP'
export const DECREMENT_STEP = 'DECREMENT_STEP'
export const DYNAMIC_ACTIVE_STEP = 'DYNAMIC_ACTIVE_STEP'
export const HANDLE_MODAL = 'HANDLE_MODAL'

// Portfolio  Types
export const LOAD_PORTFOLIO_DATA_SUCCESS = 'LOAD_PORTFOLIO_DATA_SUCCESS'
export const LOAD_PORTFOLIO_DATA_FAILED = 'LOAD_PORTFOLIO_DATA_FAILED'

export const HANDLE_ITEM_MODAL = 'HANDLE_ITEM_MODAL'
export const HANDLE_TAB_CLICK = 'HANDLE_TAB_CLICK'
export const HANDLE_TAB_CLICK_SELECTED_GROUP = 'HANDLE_TAB_CLICK_SELECTED_GROUP'
export const HANDLE_PAGINATION = 'HANDLE_PAGINATION'

export const HANDLE_PORTFOLIO_SEARCH = 'HANDLE_PORTFOLIO_SEARCH'

// Types of Blog
export const LOAD_BLOG_DATA_SUCCESS = 'LOAD_BLOG_DATA_SUCCESS'
export const LOAD_BLOG_DATA_FAILED = 'LOAD_BLOG_DATA_FAILED'
export const SEARCH_BLOG_HANDLE_CHANGE = 'SEARCH_BLOG_HANDLE_CHANGE'
export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY'
export const SELEC_TOPIC_HANDLE_FILTER = 'SELEC_TOPIC_HANDLE_FILTER'
export const SELECT_LANGUAGE_TYPE = 'SELECT_LANGUAGE_TYPE'

// Pagination
export const HANDLE_CHANGE_PAGE_NO = 'HANDLE_CHANGE_PAGE_NO'
export const HANDLE_FILTERED_POSTS = 'HANDLE_FILTERED_POSTS'
export const HANDLE_CHANGE_ITEM_PER_PAGE = 'HANDLE_CHANGE_ITEM_PER_PAGE'
export const HANDLE_CHANGE_DATE_POSTS = 'HANDLE_CHANGE_DATE_POSTS'

// Subscribe To Sned Mail Types
export const HANDLE_CHANGE_SUBSCRIBER_MAIL = 'HANDLE_CHANGE_SUBSCRIBER_MAIL'
export const HANDLE_SUBMIT_SUBSCRIBER_MAIL_SUCCESS = 'HANDLE_SUBMIT_SUBSCRIBER_MAIL_SUCCESS'
export const HANDLE_SUBMIT_SUBSCRIBER_MAIL_FAILED = 'HANDLE_SUBMIT_SUBSCRIBER_MAIL_FAILED'

export const HANDLE_INCREMENT_AND_DECREMENT = 'HANDLE_INCREMENT_AND_DECREMENT'

// Contact Form
export const HANDLE_CHANGE_CONTACT_FIELDS = 'HANDLE_CHANGE_CONTACT_FIELDS'

export const HANDLE_SUBMIT_CONTACT_FORM_SUCCESS = 'HANDLE_SUBMIT_CONTACT_FORM_SUCCESS'
export const HANDLE_SUBMIT_CONTACT_FORM_FAILED = 'HANDLE_SUBMIT_CONTACT_FORM_FAILED'
export const HANDLE_LOADER_CONTACT_FORM = 'HANDLE_LOADER_CONTACT_FORM'
export const HANDLE_CHANGE_CONTACT_FIELDS_ERROR = 'HANDLE_CHANGE_CONTACT_FIELDS_ERROR'

export const HANDLE_CLICK_CONTACT_ALERT_MESSAGE_CLEAR = 'HANDLE_CLICK_CONTACT_ALERT_MESSAGE_CLEAR'
