export const IS_LOADING_OPENED = 'IS_LOADING_OPENED'

// Navbar
export const HANDLE_MENU = 'HANDLE_MENU'

// Skills Types
export const INCREMENT_STEP = 'INCREMENT_STEP'
export const DECREMENT_STEP = 'DECREMENT_STEP'
export const DYNAMIC_ACTIVE_STEP = 'DYNAMIC_ACTIVE_STEP'
export const HANDLE_MODAL = 'HANDLE_MODAL'

// Portfolio  Types
export const LOAD_PORTFOLIO_DATA_SUCCESS = 'LOAD_PORTFOLIO_DATA_SUCCESS'
export const LOAD_PORTFOLIO_DATA_FAILED = 'LOAD_PORTFOLIO_DATA_FAILED'

export const HANDLE_ITEM_MODAL = 'HANDLE_ITEM_MODAL'
export const HANDLE_TAB_CLICK = 'HANDLE_TAB_CLICK'
export const HANDLE_TAB_CLICK_SELECTED_GROUP = 'HANDLE_TAB_CLICK_SELECTED_GROUP'
export const HANDLE_PAGINATION = 'HANDLE_PAGINATION'

export const HANDLE_PORTFOLIO_SEARCH = 'HANDLE_PORTFOLIO_SEARCH'

// Types of Blog
export const LOAD_BLOG_DATA_SUCCESS = 'LOAD_BLOG_DATA_SUCCESS'
export const LOAD_BLOG_DATA_FAILED = 'LOAD_BLOG_DATA_FAILED'
export const SEARCH_BLOG_HANDLE_CHANGE = 'SEARCH_BLOG_HANDLE_CHANGE'