export const HANDLE_DRAWER_TOGGLE = 'HANDLE_DRAWER_TOGGLE'

export const HANDLE_LOADER = 'HANDLE_LOADER'

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

// App
export const LOGIN_HANDLE_LOADER = 'LOGIN_HANDLE_LOADER'
export const LOGIN_HANDLE_CHANGE = 'LOGIN_HANDLE_CHANGE'
export const LOGIN_ERRORS_OCCURRED = 'LOGIN_ERRORS_OCCURRED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'


// Subscriptions Types
export const SUBS_IS_LOADING = 'SUBS_IS_LOADING'
export const SUBS_ERROR_OCCURRED = 'SUBS_ERROR_OCCURRED'
export const SUBS_LOAD_DATA_SUCCESS = 'SUBS_LOAD_DATA_SUCCESS'
export const SUBS_HANDLE_CHANGE_FORM = 'SUBS_HANDLE_CHANGE_FORM'
export const SUBS_HANDLE_SUBMIT_SUCCESS = 'SUBS_HANDLE_SUBMIT_SUCCESS'
export const SUBS_HANDLE_SUBMIT_FAILED = 'SUBS_HANDLE_SUBMIT_FAILED'
export const SUBS_MAIL_DELETED_SUCCESS = 'SUBS_MAIL_DELETED_SUCCESS'
export const SUBS_EDIT_EMAIL_HANDLE_CLICK = 'SUBS_EDIT_EMAIL_HANDLE_CLICK'
export const SUBS_EDIT_EMAIL_HANDLE_CHANGE = 'SUBS_EDIT_EMAIL_HANDLE_CHANGE'
export const SUBS_EDIT_EMAIL_SUCCESS = 'SUBS_EDIT_EMAIL_SUCCESS'

// Blogs Types

//Blog Of Blogs

// export const BLOGS_HANDLE_SUCCESS = 'BLOGS_HANDLE_SUCCESS'
export const BLOGS_HANDLE_ERROR = 'BLOGS_HANDLE_ERROR'
export const BLOGS_GROUP_CREATE_SUCCESS = 'BLOGS_GROUP_CREATE_SUCCESS'
export const BLOGS_GROUP_CREATE_ERROR = 'BLOGS_GROUP_CREATE_ERROR'

export const BLOGS_DATA_LOAD_TO_FIELD = 'BLOGS_DATA_LOAD_FIELD'
export const BLOGS_GROUP_UPDATE_LOADING = 'BLOGS_GROUP_UPDATE_LOADING'
export const BLOGS_TAB_HANDLE_CHANGE = 'BLOGS_TAB_HANDLE_CHANGE'
export const BLOGS_SEO_HANDLE_CHANGE = 'BLOGS_SEO_HANDLE_CHANGE'
export const BLOGS_MENU_HANDLE_CHANGE = 'BLOGS_MENU_HANDLE_CHANGE'
export const BLOGS_CREATE_HANDLE_CHANGE = 'BLOGS_CREATE_HANDLE_CHANGE'
export const BLOGS_CREATE_HANDLE_SUCCESS = 'BLOGS_CREATE_HANDLE_SUCCESS'
export const BLOGS_ALERT_HANDLE_CLOSE = 'BLOGS_ALERT_HANDLE_CLOSE'
// Group Of Blogs
export const BLOGS_GROUP_NAME_HANDLE_CHANGE = 'BLOGS_GROUP_NAME_HANDLE_CHANGE'
export const BLOGS_GROUP_UPDATE_HANDLE_CLICK = 'BLOGS_GROUP_UPDATE_HANDLE_CLICK'
export const BLOGS_GROUP_UPDATE_HANDLE_CHANGE = 'BLOGS_GROUP_UPDATE_HANDLE_CHANGE'
export const BLOGS_GROUP_CONFIRM_DIALOG_TOGGLE = 'BLOGS_GROUP_CONFIRM_DIALOG_TOGGLE'
export const BLOGS_GROUP_INDEX_HANDLE_CHANGE = 'BLOGS_GROUP_INDEX_HANDLE_CHANGE'
export const BLOGS_TAB_SELECTED_GROUP_ID = 'BLOGS_TAB_SELECTED_GROUP_ID'
// ------------------ Asyncronous Tasks For Blogs Group CRUD Oparation --------------------
// Get All Blogs
export const GET_ALL_BLOGS = 'GET_ALL_BLOGS'
// Group creation
export const BLOGS_GROUP_NAME_HANDLE_SUBMIT = 'BLOGS_GROUP_NAME_HANDLE_SUBMIT'
// Group updatable
export const BLOGS_GROUP_UPDATE_HANDLE_SUBMIT = 'BLOGS_GROUP_UPDATE_HANDLE_SUBMIT'
// Group deletable
export const BLOGS_GROUP_DELETE_HANDLE_SUCCESS = 'BLOGS_GROUP_DELETE_HANDLE_SUCCESS'

// ------------------ Asyncronous Tasks For Blogs Group Item CRUD Oparation ------------------
export const BLOGS_GET_ALL_BLOGS_POST_SUCCESS = 'BLOGS_GET_ALL_BLOGS_POST_SUCCESS'
export const BLOGS_CREATE_SUCCESS = 'BLOGS_CREATE_SUCCESS'

// Functionality handle
export const BLOGS_POST_SELECTED_EDIT_MODAL = 'BLOGS_POST_SELECTED_EDIT_MODAL'
export const BLOGS_POST_UPDATE_HANDLE_CHANGE = 'BLOGS_POST_UPDATE_HANDLE_CHANGE'
export const BLOGS_POST_UPDATE_SUCCESS = 'BLOGS_POST_UPDATE_SUCCESS'
export const BLOGS_POST_DELETE_SUCCESS = 'BLOGS_POST_DELETE_SUCCESS'

//--------- Portfolio  Types-----------
export const PORTFOLIO_CLEARATION_ALL = 'PORTFOLIO_CLEARATION_ALL'
export const PORTFOLIO_ERROR_OCCURRED = 'PORTFOLIO_ERROR_OCCURRED'
export const PORTFOLIO_LOADING_OPENED = 'PORTFOLIO_LOADING_OPENED'
export const PORTFOLIO_LOADING_TOW_OPENED = 'PORTFOLIO_LOADING_TOW_OPENED'

export const PORTFOLIO_FETCH_NEW_GROUP_DATA = 'PORTFOLIO_FETCH_NEW_GROUP_DATA'
export const PORTFOLIO_TAB_INDEX_HANDLE_CHANGE = 'PORTFOLIO_TAB_INDEX_HANDLE_CHANGE'
export const PORTFOLIO_CREATE_GROUP_HANDLE_CHANGE = 'PORTFOLIO_CREATE_GROUP_HANDLE_CHANGE'
export const PORTFOLIO_CREATED_GROUP_SUCCESS = 'PORTFOLIO_CREATED_GROUP_SUCCESS'
export const PORTFOLIO_UPDATE_SELECTED_GROUP = 'PORTFOLIO_UPDATE_SELECTED_GROUP'
export const PORTFOLIO_UPDATE_HANDLE_CHANGE = 'PORTFOLIO_UPDATE_HANDLE_CHANGE'
export const PORTFOLIO_UPDATE_GROUP_SUCCESS = 'PORTFOLIO_UPDATE_GROUP_SUCCESS'
export const PORTFOLIO_GROUP_DELETE_SUCCESS = 'PORTFOLIO_GROUP_DELETE_SUCCESS'
// Portfolio Projects Creation Types
export const PORTFOLIO_GET_ALL_PROJECTS_DATA = 'PORTFOLIO_GET_ALL_PROJECTS_DATA'
export const PORTFOLIO_CREATE_PROJECT_FILE_HANDLE_CHANGE = 'PORTFOLIO_CREATE_PROJECT_FILE_HANDLE_CHANGE'
export const PORTFOLIO_CREATE_PROJECT_HANDLE_CHANGE = 'PORTFOLIO_CREATE_PROJECT_HANDLE_CHANGE'
export const PORTFOLIO_CREATE_PROJECT_SAVE_FILES = 'PORTFOLIO_CREATE_PROJECT_SAVE_FILES'
export const PORTFOLIO_CREATE_PROJECT_HANDLE_CHANGE_IMAGE = 'PORTFOLIO_CREATE_PROJECT_HANDLE_CHANGE_IMAGE'
export const PORTFOLIO_CREATE_PROJECT_SUCCESS = 'PORTFOLIO_CREATE_PROJECT_SUCCESS'
export const PORTFOLIO_HANDLE_CHANGE_GROUP_INDEX = 'PORTFOLIO_HANDLE_CHANGE_GROUP_INDEX'
export const PORTFOLIO_HANDLE_SELECTED_GROUP = 'PORTFOLIO_HANDLE_SELECTED_GROUP'
export const PORTFOLIO_HANDLE_CLICK_EDIT_MODAL = 'PORTFOLIO_HANDLE_CLICK_EDIT_MODAL'
export const PORTFOLIO_PROJECT_UPDATE_HANDLE_CHANGE = 'PORTFOLIO_PROJECT_UPDATE_HANDLE_CHANGE'
export const PORTFOLIO_PROJECT_UPDATE_HANDLE_CHANGE_FILE = 'PORTFOLIO_PROJECT_UPDATE_HANDLE_CHANGE_FILE'
export const PORTFOLIO_PROJECT_UPDATE_HANDLE_CHANGE_FILES = 'PORTFOLIO_PROJECT_UPDATE_HANDLE_CHANGE_FILES'
export const PORTFOLIO_PROJECT_UPDATE_HANDLE_CHANGE_IMG_TITLE = 'PORTFOLIO_PROJECT_UPDATE_HANDLE_CHANGE_IMG_TITLE'
export const PROTFOLIO_PROJECT_UPDATE_HANDLE_DELETE_IMG = 'PROTFOLIO_PROJECT_UPDATE_HANDLE_DELETE_IMG'
export const PORTFOLIO_PROJECT_UPDATE_SUCCESS = 'PORTFOLIO_PROJECT_UPDATE_SUCCESS'
export const PROTFOLIO_PROJECT_DELETED_SUCCESS = 'PROTFOLIO_PROJECT_DELETED_SUCCESS'

// Contact
export const CONTACT_HANDLE_LOADER = 'CONTACT_HANDLE_LOADER'
export const CONTACT_CLEAR_MESSAGE = 'CONTACT_CLEAR_MESSAGE'
export const CONTACT_GET_DATA_SUCCESS = 'CONTACT_GET_DATA_SUCCESS'
export const CONTACT_GET_DATA_FAILED = 'CONTACT_GET_DATA_FAILED '
export const CONTACT_HANDLE_SELECTED_CONTACT_FOR_VIEW = 'CONTACT_HANDLE_SELECTED_CONTACT_FOR_VIEW '
export const CONTACT_HANDLE_SELECTED_ID_REMOVE = 'CONTACT_HANDLE_SELECTED_ID_REMOVE '
export const CONTACT_HANDLE_SUBMIT_DELETE_SUCCESS = 'CONTACT_HANDLE_SUBMIT_DELETE_SUCCESS '
export const CONTACT_HANDLE_SUBMIT_DELETE_FAILED = 'CONTACT_HANDLE_SUBMIT_DELETE_FAILED '

export const CONTACT_HANDLE_SELECTED_MAIL = 'CONTACT_HANDLE_SELECTED_MAIL'
export const CONTACT_HANDLE_UNSELECT_MAIL = 'CONTACT_HANDLE_SELECT_MAIL'
export const CONTACT_HANDLE_CHANGE_SEND_MAIL = 'CONTACT_HANDLE_CHANGE_SEND_MAIL'

export const CONTACT_HANDLE_SUBMIT_SEND_MAIL_LOADING = 'CONTACT_HANDLE_SUBMIT_SEND_MAIL_LOADING'
export const CONTACT_HANDLE_SUBMIT_SEND_MAIL_ERRORS = 'CONTACT_HANDLE_SUBMIT_SEND_MAIL_ERRORS'
export const CONTACT_HANDLE_SUBMIT_SEND_MAIL_SUCCESS = 'CONTACT_HANDLE_SUBMIT_SEND_MAIL_SUCCESS'
export const CONTACT_HANDLE_SUBMIT_SEND_MAIL_FAILED = 'CONTACT_HANDLE_SUBMIT_SEND_MAIL_FAILED'
